kind: pipeline
type: docker
name: default

steps:
  #- name: test-bedrock
  #  image: golang:alpine
  #  commands:
  #    - cd bedrockEdition
  #    - go build
  #    - go test -v
  - name: test-java
    image: golang:alpine
    commands:
      - apk add build-base # Adds gcc
      - cd javaEdition
      - go test -v ./...
  - name: test-nbt
    image: golang:alpine
    commands:
      - apk add build-base # Adds gcc
      - cd nbt
      - go test -v ./...
  - name: test-primitive
    image: golang:alpine
    commands:
      - apk add build-base # Adds gcc
      - cd primitive
      - go test -v ./...