package version119

import (
	"github.com/camdenorrb/minecraftPackets/javaEdition/protocol/common"
)

func Registry(bound common.Bound) common.PacketRegistry {

	switch bound {
	case common.ClientBound:
		return clientBound()
	case common.ServerBound:
		return serverBound()
	}

	return nil
}

func clientBound() common.PacketRegistry {

	registry := common.NewPacketRegistry()

	// Status
	registry.Register(common.StatusState, 0x00, common.ClientBoundStatusResponse)
	registry.Register(common.StatusState, 0x01, common.ClientBoundStatusPing)

	// Login
	registry.Register(common.LoginState, 0x00, common.ClientBoundLoginDisconnect)
	registry.Register(common.LoginState, 0x01, common.ClientBoundLoginEncryptionRequest)
	registry.Register(common.LoginState, 0x02, common.ClientBoundLoginSuccess)
	registry.Register(common.LoginState, 0x03, common.ClientBoundLoginSetCompression)
	registry.Register(common.LoginState, 0x04, common.ClientBoundLoginPluginRequest)

	// Play
	registry.Register(common.PlayState, 0x00, common.ClientBoundPlaySpawnEntity)
	registry.Register(common.PlayState, 0x01, common.ClientBoundPlaySpawnExperienceOrb)
	registry.Register(common.PlayState, 0x02, common.ClientBoundPlaySpawnPlayer)
	registry.Register(common.PlayState, 0x03, common.ClientBoundPlayEntityAnimation)
	registry.Register(common.PlayState, 0x04, common.ClientBoundPlayAwardStatistics)
	registry.Register(common.PlayState, 0x05, common.ClientBoundPlayAcknowledgeBlockChange)
	registry.Register(common.PlayState, 0x06, common.ClientBoundPlaySetBlockDestroyStage)
	registry.Register(common.PlayState, 0x07, common.ClientBoundPlayBlockEntityData)
	registry.Register(common.PlayState, 0x08, common.ClientBoundPlayBlockAction)
	registry.Register(common.PlayState, 0x09, common.ClientBoundPlayBlockUpdate)
	registry.Register(common.PlayState, 0x0A, common.ClientBoundPlayBossBar)
	registry.Register(common.PlayState, 0x0B, common.ClientBoundPlayChangeDifficulty)
	registry.Register(common.PlayState, 0x0C, common.ClientBoundPlayClearTitles)
	registry.Register(common.PlayState, 0x0D, common.ClientBoundPlayCommandSuggestionsResponse)
	registry.Register(common.PlayState, 0x0E, common.ClientBoundPlayCommands)
	registry.Register(common.PlayState, 0x0F, common.ClientBoundPlayCloseContainer)
	registry.Register(common.PlayState, 0x10, common.ClientBoundPlaySetContainerContent)
	registry.Register(common.PlayState, 0x11, common.ClientBoundPlaySetContainerProperty)
	registry.Register(common.PlayState, 0x12, common.ClientBoundPlaySetContainerSlot)
	registry.Register(common.PlayState, 0x13, common.ClientBoundPlaySetCooldown)
	registry.Register(common.PlayState, 0x14, common.ClientBoundPlayChatSuggestions)
	registry.Register(common.PlayState, 0x15, common.ClientBoundPlayPluginMessage)
	registry.Register(common.PlayState, 0x16, common.ClientBoundPlayDeleteMessage)
	registry.Register(common.PlayState, 0x17, common.ClientBoundPlayDisconnect)
	registry.Register(common.PlayState, 0x18, common.ClientBoundPlayDisguisedChatMessage)
	registry.Register(common.PlayState, 0x19, common.ClientBoundPlayEntityEvent)
	registry.Register(common.PlayState, 0x1A, common.ClientBoundPlayExplosion)
	registry.Register(common.PlayState, 0x1B, common.ClientBoundPlayUnloadChunk)
	registry.Register(common.PlayState, 0x1C, common.ClientBoundPlayGameEvent)
	registry.Register(common.PlayState, 0x1D, common.ClientBoundPlayOpenHorseScreen)
	registry.Register(common.PlayState, 0x1E, common.ClientBoundPlayInitializeWorldBorder)
	registry.Register(common.PlayState, 0x1F, common.ClientBoundPlayKeepAlive)
	registry.Register(common.PlayState, 0x20, common.ClientBoundPlayChunkDataAndUpdateLight)
	registry.Register(common.PlayState, 0x21, common.ClientBoundPlayWorldEvent)
	registry.Register(common.PlayState, 0x22, common.ClientBoundPlayParticle)
	registry.Register(common.PlayState, 0x23, common.ClientBoundPlayUpdateLight)
	registry.Register(common.PlayState, 0x24, common.ClientBoundPlayLogin)
	registry.Register(common.PlayState, 0x25, common.ClientBoundPlayMapData)
	registry.Register(common.PlayState, 0x26, common.ClientBoundPlayMerchantOffers)
	registry.Register(common.PlayState, 0x27, common.ClientBoundPlayUpdateEntityPosition)
	registry.Register(common.PlayState, 0x28, common.ClientBoundPlayUpdateEntityPositionAndRotation)
	registry.Register(common.PlayState, 0x29, common.ClientBoundPlayUpdateEntityRotation)
	registry.Register(common.PlayState, 0x2A, common.ClientBoundPlayMoveVehicle)
	registry.Register(common.PlayState, 0x2B, common.ClientBoundPlayOpenBook)
	registry.Register(common.PlayState, 0x2C, common.ClientBoundPlayOpenWindow)
	registry.Register(common.PlayState, 0x2D, common.ClientBoundPlayOpenSignEditor)
	registry.Register(common.PlayState, 0x2E, common.ClientBoundPlayPing)
	registry.Register(common.PlayState, 0x2F, common.ClientBoundPlayPlaceGhostRecipe)
	registry.Register(common.PlayState, 0x30, common.ClientBoundPlayPlayerAbilities)
	registry.Register(common.PlayState, 0x31, common.ClientBoundPlayPlayerChatMessage)
	registry.Register(common.PlayState, 0x32, common.ClientBoundPlayEndCombat)
	registry.Register(common.PlayState, 0x33, common.ClientBoundPlayEnterCombat)
	registry.Register(common.PlayState, 0x34, common.ClientBoundPlayCombatDeath)
	registry.Register(common.PlayState, 0x35, common.ClientBoundPlayPlayerInfoRemove)
	registry.Register(common.PlayState, 0x36, common.ClientBoundPlayPlayerInfoUpdate)
	registry.Register(common.PlayState, 0x37, common.ClientBoundPlayLookAt)
	registry.Register(common.PlayState, 0x38, common.ClientBoundPlaySynchronizePlayerPosition)
	registry.Register(common.PlayState, 0x39, common.ClientBoundPlayUpdateRecipeBook)
	registry.Register(common.PlayState, 0x3A, common.ClientBoundPlayRemoveEntities)
	registry.Register(common.PlayState, 0x3B, common.ClientBoundPlayRemoveEntityEffect)
	registry.Register(common.PlayState, 0x3C, common.ClientBoundPlayResourcePack)
	registry.Register(common.PlayState, 0x3D, common.ClientBoundPlayRespawn)
	registry.Register(common.PlayState, 0x3E, common.ClientBoundPlaySetHeadRotation)
	registry.Register(common.PlayState, 0x3F, common.ClientBoundPlayUpdateSectionBlocks)
	registry.Register(common.PlayState, 0x40, common.ClientBoundPlaySelectAdvancementTab)
	registry.Register(common.PlayState, 0x41, common.ClientBoundPlayServerData)
	registry.Register(common.PlayState, 0x42, common.ClientBoundPlaySetActionBarText)
	registry.Register(common.PlayState, 0x43, common.ClientBoundPlaySetBorderCenter)
	registry.Register(common.PlayState, 0x44, common.ClientBoundPlaySetBorderLerpSize)
	registry.Register(common.PlayState, 0x45, common.ClientBoundPlaySetBorderSize)
	registry.Register(common.PlayState, 0x46, common.ClientBoundPlaySetBorderWarningDelay)
	registry.Register(common.PlayState, 0x47, common.ClientBoundPlaySetBorderWarningDistance)
	registry.Register(common.PlayState, 0x48, common.ClientBoundPlaySetCamera)
	registry.Register(common.PlayState, 0x49, common.ClientBoundPlaySetHeldItem)
	registry.Register(common.PlayState, 0x4A, common.ClientBoundPlaySetCenterChunk)
	registry.Register(common.PlayState, 0x4B, common.ClientBoundPlaySetRenderDistance)
	registry.Register(common.PlayState, 0x4C, common.ClientBoundPlaySetDefaultSpawnPosition)
	registry.Register(common.PlayState, 0x4D, common.ClientBoundPlayDisplayObjective)
	registry.Register(common.PlayState, 0x4E, common.ClientBoundPlaySetEntityMetadata)
	registry.Register(common.PlayState, 0x4F, common.ClientBoundPlayLinkEntities)
	registry.Register(common.PlayState, 0x50, common.ClientBoundPlaySetEntityVelocity)
	registry.Register(common.PlayState, 0x51, common.ClientBoundPlaySetEquipment)
	registry.Register(common.PlayState, 0x52, common.ClientBoundPlaySetExperience)
	registry.Register(common.PlayState, 0x53, common.ClientBoundPlaySetHealth)
	registry.Register(common.PlayState, 0x54, common.ClientBoundPlayUpdateObjectives)
	registry.Register(common.PlayState, 0x55, common.ClientBoundPlaySetPassengers)
	registry.Register(common.PlayState, 0x56, common.ClientBoundPlayUpdateTeams)
	registry.Register(common.PlayState, 0x57, common.ClientBoundPlayUpdateScore)
	registry.Register(common.PlayState, 0x58, common.ClientBoundPlaySetSimulationDistance)
	registry.Register(common.PlayState, 0x59, common.ClientBoundPlaySetSubtitleText)
	registry.Register(common.PlayState, 0x5A, common.ClientBoundPlayUpdateTime)
	registry.Register(common.PlayState, 0x5B, common.ClientBoundPlaySetTitleText)
	registry.Register(common.PlayState, 0x5C, common.ClientBoundPlaySetTitleAnimationTimes)
	registry.Register(common.PlayState, 0x5D, common.ClientBoundPlayEntitySoundEffect)
	registry.Register(common.PlayState, 0x5E, common.ClientBoundPlaySoundEffect)
	registry.Register(common.PlayState, 0x5F, common.ClientBoundPlayStopSound)
	registry.Register(common.PlayState, 0x60, common.ClientBoundPlaySystemChatMessage)
	registry.Register(common.PlayState, 0x61, common.ClientBoundPlaySetTabListHeaderAndFooter)
	registry.Register(common.PlayState, 0x62, common.ClientBoundPlayTagQueryResponse)
	registry.Register(common.PlayState, 0x63, common.ClientBoundPlayPickupItem)
	registry.Register(common.PlayState, 0x64, common.ClientBoundPlayTeleportEntity)
	registry.Register(common.PlayState, 0x65, common.ClientBoundPlayUpdateAttributes)
	registry.Register(common.PlayState, 0x66, common.ClientBoundPlayUpdateAttributes)
	registry.Register(common.PlayState, 0x67, common.ClientBoundPlayFeatureFlags)
	registry.Register(common.PlayState, 0x68, common.ClientBoundPlayEntityEffect)
	registry.Register(common.PlayState, 0x69, common.ClientBoundPlayUpdateRecipes)
	registry.Register(common.PlayState, 0x6A, common.ClientBoundPlayUpdateTags)

	return registry
}

func serverBound() common.PacketRegistry {

	registry := common.NewPacketRegistry()

	// Handshaking
	registry.Register(common.HandshakingState, 0x00, common.ServerBoundHandshake)
	registry.Register(common.HandshakingState, 0xFE, common.ServerBoundHandshakeLegacyServerListPing)

	// Status
	registry.Register(common.StatusState, 0x00, common.ServerBoundStatusRequest)
	registry.Register(common.StatusState, 0x01, common.ServerBoundStatusPing)

	// Login
	registry.Register(common.LoginState, 0x00, common.ServerBoundLoginStart)
	registry.Register(common.LoginState, 0x01, common.ServerBoundLoginEncryptionResponse)
	registry.Register(common.LoginState, 0x02, common.ServerBoundLoginPluginResponse)

	// Play
	registry.Register(common.PlayState, 0x00, common.ServerBoundPlayConfirmTeleportation)
	registry.Register(common.PlayState, 0x01, common.ServerBoundPlayQueryBlockEntityTag)
	registry.Register(common.PlayState, 0x02, common.ServerBoundPlayChangeDifficulty)
	registry.Register(common.PlayState, 0x03, common.ServerBoundPlayMessageAcknowledgement)
	registry.Register(common.PlayState, 0x04, common.ServerBoundPlayChatCommand)
	registry.Register(common.PlayState, 0x05, common.ServerBoundPlayChatMessage)
	registry.Register(common.PlayState, 0x06, common.ServerBoundPlayClientCommand)
	registry.Register(common.PlayState, 0x07, common.ServerBoundPlayClientInformation)
	registry.Register(common.PlayState, 0x08, common.ServerBoundPlayCommandSuggestionsRequest)
	registry.Register(common.PlayState, 0x09, common.ServerBoundPlayClickContainerButton)
	registry.Register(common.PlayState, 0x0A, common.ServerBoundPlayClickContainer)
	registry.Register(common.PlayState, 0x0B, common.ServerBoundPlayCloseContainer)
	registry.Register(common.PlayState, 0x0C, common.ServerBoundPlayPluginMessage)
	registry.Register(common.PlayState, 0x0D, common.ServerBoundPlayEditBook)
	registry.Register(common.PlayState, 0x0E, common.ServerBoundPlayQueryEntityTag)
	registry.Register(common.PlayState, 0x0F, common.ServerBoundPlayInteractEntity)
	registry.Register(common.PlayState, 0x10, common.ServerBoundPlayJigsawGenerate)
	registry.Register(common.PlayState, 0x11, common.ServerBoundPlayKeepAlive)
	registry.Register(common.PlayState, 0x12, common.ServerBoundPlayLockDifficulty)
	registry.Register(common.PlayState, 0x13, common.ServerBoundPlaySetPlayerPosition)
	registry.Register(common.PlayState, 0x14, common.ServerBoundPlaySetPlayerPositionAndRotation)
	registry.Register(common.PlayState, 0x15, common.ServerBoundPlaySetPlayerRotation)
	registry.Register(common.PlayState, 0x16, common.ServerBoundPlaySetPlayerOnGround)
	registry.Register(common.PlayState, 0x17, common.ServerBoundPlayMoveVehicle)
	registry.Register(common.PlayState, 0x18, common.ServerBoundPlayPaddleBoat)
	registry.Register(common.PlayState, 0x19, common.ServerBoundPlayPickItem)
	registry.Register(common.PlayState, 0x1A, common.ServerBoundPlayPlaceRecipe)
	registry.Register(common.PlayState, 0x1B, common.ServerBoundPlayPlayerAbilities)
	registry.Register(common.PlayState, 0x1C, common.ServerBoundPlayPlayerAction)
	registry.Register(common.PlayState, 0x1D, common.ServerBoundPlayPlayerCommand)
	registry.Register(common.PlayState, 0x1E, common.ServerBoundPlayPlayerInput)
	registry.Register(common.PlayState, 0x1F, common.ServerBoundPlayPong)
	registry.Register(common.PlayState, 0x20, common.ServerBoundPlayPlayerSession)
	registry.Register(common.PlayState, 0x21, common.ServerBoundPlayChangeRecipeBookSettings)
	registry.Register(common.PlayState, 0x22, common.ServerBoundPlaySetSeenRecipe)
	registry.Register(common.PlayState, 0x23, common.ServerBoundPlayRenameItem)
	registry.Register(common.PlayState, 0x24, common.ServerBoundPlayResourcePack)
	registry.Register(common.PlayState, 0x25, common.ServerBoundPlaySeenAdvancements)
	registry.Register(common.PlayState, 0x26, common.ServerBoundPlaySelectTrade)
	registry.Register(common.PlayState, 0x27, common.ServerBoundPlaySetBeaconEffect)
	registry.Register(common.PlayState, 0x28, common.ServerBoundPlaySetHeldItem)
	registry.Register(common.PlayState, 0x29, common.ServerBoundPlayProgramCommandBlock)
	registry.Register(common.PlayState, 0x2A, common.ServerBoundPlayProgramCommandBlockMinecart)
	registry.Register(common.PlayState, 0x2B, common.ServerBoundPlaySetCreativeModeSlot)
	registry.Register(common.PlayState, 0x2C, common.ServerBoundPlayProgramJigsawBlock)
	registry.Register(common.PlayState, 0x2D, common.ServerBoundPlayProgramStructureBlock)
	registry.Register(common.PlayState, 0x2E, common.ServerBoundPlayUpdateSign)
	registry.Register(common.PlayState, 0x2F, common.ServerBoundPlaySwingArm)
	registry.Register(common.PlayState, 0x30, common.ServerBoundPlayTeleportToEntity)
	registry.Register(common.PlayState, 0x31, common.ServerBoundPlayUseItemOn)
	registry.Register(common.PlayState, 0x32, common.ServerBoundPlayUseItem)

	return registry
}
